### ISSUE TITLE
Duplicated first line (In filename and content)

### ISSUE THREAD

**Issue by santiyounger** [lynchjames/note-refactor-obsidian#12]
Hey, 

**Thank you so much for making this amazing plugin.** It's by far my favorite and I use it all the time.

The following is perhaps more of a feature request, which I believe was already possible in a past version.

## Example

I have the following in my daily note:

```
this is a new topic

here's some more stuff about that content
and here's some more.
```

Now when I use  "Extract selection to new note - first line as filename"

I get the following

```
NOTE TILE: this is a new topic
this is a new topic

here's some more stuff about that content
and here's some more.
```

**I'd like the first line of the content not to repeat,** so that it becomes only the file name, but not duplicate  the first line it in the content of the note.

### Resulting in this

```
NOTE TILE: this is a new topic

here's some more stuff about that content
and here's some more.
```

 I believe the first released it available with manual download of folder for  0.9.7 had this way of doing things, but I might be wrong.

Would love to have this option, whether that is through the settings, or as an extra function in the command palette.

Thank you so much for your hard work!

-- Santi

**Comment by lynchjames** [comment]
Do you have this setting enabled?
![image](https://user-images.githubusercontent.com/113271/97782632-88d48d00-1b8a-11eb-8c01-431a167d85a7.png)

Turning it off should give you the behaviour you are looking for.

**Comment by lynchjames** [comment]
As of 0.9.10 you can now update the plugin in the Obsidian app by:
1. Going to `Third-party plugins > Community plugins`
1. Selecting Note Refactor and clicking update (new version should be 1.2.0)
1. Turn the plugin off and on again to fully reload it

**Comment by lynchjames** [comment]
Actually, the first line would still have been included even with the heading setting turned off. I've added another setting to control whether to include first line of selected content in note content.

Available in latest release.

**Comment by lynchjames** [comment]
This can now be done explicitly with Exclude First Line configuration setting, see [usage table](https://github.com/lynchjames/note-refactor-obsidian#usage) for details.

**Comment by santiyounger** [comment]
thank you so much, that is exactly what I needed! appreciate you taking the time to add this, it's great
