### ISSUE TITLE
Renaming file doesn't update in other notes

### ISSUE THREAD

**Issue by santiyounger** [lynchjames/note-refactor-obsidian#18]
I noticed that there is a strange behaviour after using "Extract selection to new note - first line as filename" when it comes to renaming file names

## Expected Behaviour

I extract the content from daily note, now in the newly created note I correct a typo in the filename title.
after renaming the file
I get obsidian notification, saying this link has been updated in [[links]] made to it from other notes

## Current Behaviour

The extraction into new file works great, but when I correct the typo in filename, there's no rename update accross mentions of this note.
If I go back to my daily note where I created the extraction, now the filename has changed so the [[ link]] In daily note is broken

## Workaround
If I reload obsidian or restart it fully, now I can rename it and it updates correctly, but it's an extra step that I don't always remember to do and I end up breaking links.

## version

I'm using version 1.4.4
with obsidian 0.9.10

thank you so much for the excellent plugin, I use it all the time!

**Comment by lynchjames** [comment]
Thanks for raising this with lots of useful info to try and track this down. I have a few more questions:

- Can you confirm the plugin settings you currently have? 
- Did you notice if the file name and text in the link on the daily note were different? 
- Were there any non-alphanumeric characters on the line that was used for the filename?
- Is a backlink to the daily displayed correctly for the new note when this happens? 

First thing that comes to mind is that the filename may be generated with slightly different content to what is placed in the internal link, which would cause the two notes not to be linked correctly. However, the fact that it works if you reload Obsidian may mean that the new file is not registered with the Obsidian vault correctly. I will try and replicate.

**Comment by santiyounger** [comment]
Hey @lynchjames thanks for taking the time to look into this.
I just updated to version 1.4.5 and it seems to work without any issues. 

I would still have to test it some more to see if there aren't any problems I might not be aware of, 

I'll still answer the questions just in case, since users I'm not sure if there might still be usecases where things break. 

> Can you confirm the plugin settings you currently have?

![image](https://user-images.githubusercontent.com/51902730/97994096-eea35d80-1db2-11eb-8b51-9e826d232253.png)

> Did you notice if the file name and text in the link on the daily note were different?

on version 1.4.4 initially the filename was correct and exactly the same, it was only once I wanted to rename the file that the link wasn't updated, but now in version 1.4.5 it works without an issue.

>  Were there any non-alphanumeric characters on the line that was used for the filename?

I run a few tests, since I do use symbols for some notes such as: ⟐ ✪ ☉ ⊞ 
with 1.4.5 it seems to work without any issues.

 > Is a backlink to the daily displayed correctly for the new note when this happens?

with 1.4.5 now it does

---

Hopefully this usecase example helps, but again things seems to work great so far with version 1.4.5 feel free to close this issue, from my side things seem to be fixed

Thank you

**Comment by lynchjames** [comment]
Thanks! Will close.
