### ISSUE TITLE
Extract note into the same folder don't work

### ISSUE THREAD

**Issue by Yeboster** [lynchjames/note-refactor-obsidian#23]
Hello,

I really like this plugin and it's very helpful to refactor notes. Unfortunately when I select "Same folder as current file" the extraction into a file (both with and without auto filename) just do nothing. Not an error or message is thrown.
On the other hand, the default obsidian option to save new files into same folder location works well.

I'm using Obsidian 0.9.10 on MacOs Catalina and I've created a test vault with only this plugin installed.

What could be the reason ? Is there a way to check the logs ?

The following gif shows this behaviour.

![Screen-Recording-2020-11-07-at-1](https://user-images.githubusercontent.com/23556525/98440439-f89dc700-20f8-11eb-80d4-9590f3fcb532.gif)

**Comment by lynchjames** [comment]
Hi. Thanks for raising this with the gif to show what actions you took. 

I can recreate the issue so will investigate further and then, hopefully, add a fix.

**Comment by lynchjames** [comment]
Face palm bug of not using the correct variable for the current view to get the same folder to save the new note.

Fix is in 1.4.6.
