### ISSUE TITLE
Enhancement Suggestion

### ISSUE THREAD

**Issue by q7z** [lynchjames/note-refactor-obsidian#27]
Is there a way to extract the note to an already existing file? Or a way to refract the heading into the note with the same name?

**Comment by Bejasc** [comment]
+1 for this, though the suggestion could be formatted a little better.

**Comment by lynchjames** [comment]
In [1.6.0](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.6.0), If an existing note is selected, extracted/split content will be appended to the existing note.
