### ISSUE TITLE
Changing display mode latex into inline latex

### ISSUE THREAD

**Issue by ColeFaraday** [lynchjames/note-refactor-obsidian#28]
When creating a refactored note with the following settings

![image](https://user-images.githubusercontent.com/15152541/99969310-ef705380-2da2-11eb-8d5b-c66492bfa525.png)

Display mode latex code is changed to inline latex code. This happens with the following simple test case 

![image](https://user-images.githubusercontent.com/15152541/99969499-38280c80-2da3-11eb-919f-55f73a777c9c.png)

which after refactoring gets turned into

![image](https://user-images.githubusercontent.com/15152541/99969540-49711900-2da3-11eb-9834-c7542865d200.png)

The display mode latex is changed to inline, and the inline isn't changed. All other plugins were disabled during testing.

**Comment by lynchjames** [comment]
Should be fixed in [1.5.2](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.5.2).
