### ISSUE TITLE
Support for markdown links

### ISSUE THREAD

**Issue by finn-matti** [lynchjames/note-refactor-obsidian#29]
Great plugin, however I am missing an option to use markdown links instead of Wiki-Links. For a markdown link to work we would need to make sure that we respect the New Link Format setting (shortest, relative, absolute path) and we need to make sure that we UrlEncode the actual link. Example:

Instead of creating a new note that is linked like so:

```
[[note with spaces]]
```

we would create a link like this:

```
[note with spaces](note%20with%20spaces.md)
```

As said above this option would need to consider the New Link Format setting.

**Comment by lynchjames** [comment]
This is now supported in [1.7.0](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.7.0).
