### ISSUE TITLE
template to refactored note not working

### ISSUE THREAD

**Issue by liutiming** [lynchjames/note-refactor-obsidian#31]
Thanks a lot for this awesome tool!

OS: Windows 10
Obsidian Version: 0.9.17
Plugin version: 1.5.2

template:
```
link to original note:
[[{{title}}]]
```

used ctrl + shift + c to create new note from selection and tried on two vaults (one of which is a template vault with no other community plug-in installed)

would love to provide more info if needed!

**Comment by lynchjames** [comment]
Is this the "Refactored note template" in settings? In order to include the refactored note content as well as a link to the original note, you would need to have this as the template:

```
{{new_note_content}} 

link to original note:
[[{{title}}]]
```

**Comment by liutiming** [comment]
thanks for reply! 
yes it is... 
![image](https://user-images.githubusercontent.com/39947942/102007968-3bb90e80-3d25-11eb-9e20-67622b48516b.png)

**Comment by dsteinbock** [comment]
LOVE the new append feature and modal. I, too, am experiencing an issue w/ templates in the new version, specifically the "Note link template." My templates were working fine before the update. Currently, when I invoke the "extract selection to new note, content only" command:

* Templates work as expected for *appending* to existing note. Target note opens in a new pane. Template are applied to source and target notes. 
* Problem is when *creating* a new note. Selection *is* successfully copied to new note and 'refactored note template' is applied BUT target note is *not* opened in a new pane. 'Note link template' is *not* applied to source note. Source note remains unchanged. 

Here are my templates (the latter, just for testing):
Note link template:
```
(copied to → [[{{new_note_title}}]]:)

{{new_note_content}}

(end copy)
```

Refactored note template:
```
NEW:
{{new_note_content}}
```

**Comment by lynchjames** [comment]
This was indeed a bug which, ironically, I introduced while refactoring code for the new fuzzy suggest modal. 

This should be fixed in [1.6.1](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.6.1).

**Comment by liutiming** [comment]
@lynchjames thanks so much yes it was fixed! However, with update to 1.6.1, there is no more option to add prefixer to the file names for the following command?
![image](https://user-images.githubusercontent.com/39947942/103038394-40bc6000-4566-11eb-8fad-1217d47039bb.png)

**Comment by lynchjames** [comment]
The file prefix from settings should be added for notes created when using one of the Note Refactor commands, including those that open the fuzzy suggest modal. 

However, the prefix is not currently displayed on the fuzzy suggest modal. I could add that if needed. Can you create a separate issue if you would like the prefix to be presented on the modal or if there are other issues with the prefix not being applied correctly?

**Comment by liutiming** [comment]
Thanks!

**Comment by xidlegend** [comment]
Instead of entereing the template in this field, could you add the option to import template from a file? I use `templater` plugin, and all my new files, have some YAML metadata, I want it to be consistent with refactored notes. I could hard-code copy it, but that defeats the purpose a little of templates.

![image](https://user-images.githubusercontent.com/26184016/147871551-b7dccfde-22a3-479e-90b8-b35e3f5f2045.png)
👆 this is what i am talking about

Note refactor does not respect, the newNote template for some reason, and does let me link to the template. This would be a great addition to the plugin
Thanks
