### ISSUE TITLE
Fully autogenerated new note names

### ISSUE THREAD

**Issue by approximate** [lynchjames/note-refactor-obsidian#37]
Hi @lynchjames ,

first off, thanks a lot for the great plugin! I started using it a few month ago, and it makes some of my workflows really easy.

Now I wanted to use this plugin to implement a proto-workflow for [incremental reading](https://supermemo.guru/wiki/Incremental_reading) (**IR**). Read the linked page for more background info, but here's the skinny:
1. I get a long-ish article into Obsidian note (e.g. via MarkDownload)
2. I start reading a note, extracting smaller pieces of text (sections, paragraphs, sencences) into new notes using this plugin. The original note gets the (transcluded) link to the extracted note (and vice versa if I want to) so I don't lose the link chain in case I find the context relevant.
3. when reading a note, I remove text that's not needed, rewrite what's badly worded, and make Anki cards when the content is good enough. if there's nothing in the note I want to keep or remember, I delete the note.
4. when bored/done with this note, I move on to other notes, i.e. go back to step (2).

While not completely true to the actual IR algorithm (no priority-based SR queue!), this is a "good enough" implementation for me: I can use Better Random Note plugin to show me a new IR note to read in step (2) by using tags or folders, and I use Obsidian to Anki plugin to create Anki notes for the actual SRS stuff in step (3).

What is important in this workflow are two things:
1. The extracts (new notes) are created without any intervention on my part
2. They are transient by nature - they are "fleeting notes" that are not supposed to be kept forever, but only until I process (incrementally read) them completely. Thus, they don't even need a meaningful name, only some kind of unique ID for linking.

I can ***almost*** have this whole workflow in Obsidian, but there's one showstopper: with the current plugin version, I have to either specify the note title for the new note manually (`Extract selection - content only` command), which introduces very annoying friction in my IR process (I get interrupted and have to come up with a name that doesn't exist yet), or the plugin would reuse the first line as a title (`Extract selection - first line as file name` command), which is never useful, and sometimes not even possible (when there's no real heading or section name and the first line on the extract is too long and exceeds the max allowed filename length, so the new note file can't even be created).

This all would be solved when a new note could get a fully autogenerated name without using the note text  (the setting for the file name prefix is already there!): e.g. using Zettelkasten-like time-based note name (I'll go with `YYYYMMDDHHmmss` or even `X` to avoid conflicts). Don't ask the user and don't use the first line of the extracted text, just generate a new note name and move on.

This could be a setting (`Generate filenames using timestamp only`) or a new command (`Extract selection - autogenerated filename`) or even a combination of both. I would even send you a PR if I knew TypeScript =)

And again, thanks a lot for the plugin!

**Comment by approximate** [comment]
I have actually buckled down and submitted a new PR #38 with the feature. I have tested it on my vault, it works fine. 

Thanks!

**Comment by lynchjames** [comment]
Thanks for the PR!

This has now been release in [1.7.0](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.7.0).
