### ISSUE TITLE
Automatically adjust heading levels for the newly created note

### ISSUE THREAD

**Issue by wenlzhang** [lynchjames/note-refactor-obsidian#39]
In the selected note content, the highest level of heading may be Level 4 header. However, in the newly created note, the desired level may be Level 2 header. Therefore, it would be great if this can be automatically converted.

Specifically, the old note content to be split may be:
```
#### Header Level 4

Note.

##### Header Level 5

Note.

```

The new note content may be:
```
# Header Level 1 (this may be created by using the template)

## Header Level 2

Note.

### Header Level 3

Note.

```

**Comment by lynchjames** [comment]
Added in 1.8.1
