### ISSUE TITLE
First line lost during extraction

### ISSUE THREAD

**Issue by tgrosinger** [lynchjames/note-refactor-obsidian#4]
# Observed Behavior

If `include heading` is disabled and the `content only` refactor is used, the first line is lost.

# Desired Behavior

It should be copied as is, without converting into a heading.

**Comment by lynchjames** [comment]
Thanks for reporting this!

I was able to recreate the issue and I have a fix in the [latest release 1.1.2](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.1.2).

Let me know if it has resolved the bug and I'll close this issue.

**Comment by tgrosinger** [comment]
Looks great, thank you 👍 

I did open #5 though 🙃
