### ISSUE TITLE
UID filename only for the new note

### ISSUE THREAD

**Issue by dzintars** [lynchjames/note-refactor-obsidian#42]
Is there a way to disable the file name from the new note file name?

I would like to have file names just with prefix `{{date:YYYYMMDDHHmmss}}` without the actual title.
![image](https://user-images.githubusercontent.com/547420/107511503-3dc90d80-6bae-11eb-8386-e2d14e9f7a6a.png)
I would like to see there a simple toggle to exclude the `{{new_note_title}}` from the new note file name.
If pattern in not set, then just use some default like timestamp.

**Comment by Krishnu-hm** [comment]
This! Even I would prefer if all the file names in my vault were UIDs!!

**Comment by dzintars** [comment]
@Krishnu-hm Like this? 😃 
![image](https://user-images.githubusercontent.com/547420/108830304-df4e5700-75d1-11eb-884a-36344ef5d222.png)

**Comment by approximate** [comment]
> Is there a way to disable the file name from the new note file name?

There's a PR #38 that does just this. 

> I would like to see there a simple toggle to exclude the `{{new_note_title}}` from the new note file name.
> If pattern in not set, then just use some default like timestamp.

This is not implemented in that PR (yet), but I might add this in the future.

**Comment by dzintars** [comment]
Hmm... probably i did something wrong, but i still can't figure out how to enforce `prefix-only` file names (the only issue i have). I think i read the docs several times. 😃 . I've noticed that there is also built-in Note composer plugin, but that does not do the job either.
So, to be clear - is there a way to get from:
![image](https://user-images.githubusercontent.com/547420/134815338-2623598f-20b8-40ea-bb8c-cb4dc83708fe.png)
to:
![image](https://user-images.githubusercontent.com/547420/134815347-8fd417d4-011c-4831-8efd-c71ec9810e9a.png)
