### ISSUE TITLE
Don't duplicate headings when extracting

### ISSUE THREAD

**Issue by tgrosinger** [lynchjames/note-refactor-obsidian#5]
# Observed behavior

With "Include Heading" enabled, and the "Heading format" set to "#".
With content such as

```
# My Content
For a new note
```

When selected and the command "Extract selection to new note - content only" is run, the new note will have "# # " on the first line.

# Expected behavior

Detect if the line being extracted is already a header (using the specified heading format) and avoid duplicating.

Extra-awesome would be if I extract `## My header` and it converts it into `# My header` when that setting is enabled.

**Comment by lynchjames** [comment]
Agree with the expected behaviour to avoid heading dupes and I think it would be easier to detect and strip out headings from the first line to respect heading format if it's enabled in settings. 

I'll make the change.
