### ISSUE TITLE
Current update fails

### ISSUE THREAD

**Issue by brimwats** [lynchjames/note-refactor-obsidian#53]
I tried to update to the current version, but it failed. So I uninstalled it and then tried to reinstall from scratch and it also fails.

**Comment by lynchjames** [comment]
Which version of Obsidian are you using?

Are there any console errors when you try to install or update the plugin?

**Comment by brimwats** [comment]
this seems to have been related to the github outage yday, and seems to work now

**Comment by lynchjames** [comment]
Great!
