### ISSUE TITLE
User should define directory for note

### ISSUE THREAD

**Issue by mafsi** [lynchjames/note-refactor-obsidian#6]
Please allow user to define a directory to save notes & Automatically add subdirs according to timestamp:
1. User defined directory
   - 1.1. DD-MMMM-YYYY // Subdir
     - DDMMMYYYYHHmm-Note saved

This will be very useful for processing/ incubation of note.

**Comment by lynchjames** [comment]
I have split this out into 3 other issues:
- #8 Config setting for new note location
- #9 Specified folder location for new notes to allow date formatting
- #10 Zettelkasten ID prefixer for new notes

I have mostly completed #8 and #9 except for one bug with the file explorer not updating after creating a file straight away after creating a folder. I will try and fix this before releasing #8 and #9 and then looking at #10.

**Comment by lynchjames** [comment]
All 3 linked issues closed with release 1.4.2.
