### ISSUE TITLE
Content only partially extracted

### ISSUE THREAD

**Issue by lynchjames** [lynchjames/note-refactor-obsidian#7]
# Observed behaviour
Using either the first line or content only extraction, certain selected note content is only partially extracted.

# Expected behaviour
The entirety of the selection should be extracted into the new note.

**Comment by DutchPete** [comment]
[Charisma - which type to don.md.zip](https://github.com/lynchjames/note-refactor-obsidian/files/5465705/Charisma.-.which.type.to.don.md.zip)

**Comment by lynchjames** [comment]
@DutchPete thank you for sharing the example note. Can you confirm this is happening when you are selecting note content while the pane is in editor mode? 

I can only replicate this issue when attempting to copy note content in preview mode.

**Comment by DutchPete** [comment]
James, yes, it happens in Edit mode.

I assume the font type used in Edit mode is of no influence: correct?

**Comment by lynchjames** [comment]
There could be an issue due to custom css if you have classes targeting Code Mirror editor elements. Have you tried using the plugin with the Custom CSS setting turned off?

**Comment by DutchPete** [comment]
I did try it yesterday without custom CSS - no luck. I tried it again today without custom CSS: 1x it worked, after that not anymore.

Yes, I have code mirror elements. FYI, I have attached my CSS sheet. If you have time maybe you could have a look; if you don't have time I understand.


[obsidian.css.zip](https://github.com/lynchjames/note-refactor-obsidian/files/5469059/obsidian.css.zip)

**Comment by lynchjames** [comment]
Thanks for sharing your CSS. Since this issue results in note content being lost (although you can undo in the source note to recover it) I'm keen to try and replicate and resolve it.

I will try your CSS in a test vault and hopefully I can recreate the bug.

**Comment by DutchPete** [comment]
Thanks for your help, James. If we can get it to work (i.e. you spotting the code issue, me making amendments) I will be very happy because I have quite a few (very) long notes that I want to split into smaller units.

**Comment by lynchjames** [comment]
I was able to replicate something like the issue you were seeing with the cursor on empty lines. 

I've put a fix in the [latest release 1.2.0](https://github.com/lynchjames/note-refactor-obsidian/releases/tag/1.2.0) along with some other changes.

Can you update to this version of the plugin and see if the issue has been resolved for you?

**Comment by lynchjames** [comment]
Sorry you are still having this issue. 

Would you be able to post a screen capture video or animated gif of what you’re seeing? I can then try again to replicate using the example content you provided.

**Comment by DutchPete** [comment]
Sorry, I missed your info about 1.2.0. I'll try that out 1st, then let you know.
Edit: I updated to 1.2.8 and tested on a default (= no custom CSS) vault. No luck.

Attached is a crummy GIF, but it does show that the new note is created. It has the right title, there is no excised content from the source note.

![note-refac](https://user-images.githubusercontent.com/10794265/97803240-76715680-1c51-11eb-84fa-54f1baad577c.gif)

**Comment by lynchjames** [comment]
I can only see a small part of the screen in that gif. Could you share one of the entire window?

**Comment by DutchPete** [comment]
Sorry about that. Here is a better one:

[note-refac.gif.zip](https://github.com/lynchjames/note-refactor-obsidian/files/5470877/note-refac.gif.zip)

**Comment by lynchjames** [comment]
Same issue with the size of the gif in the zip. 

I have just made another release (1.3.0). Could you try updating and check your usage against the [table in the README](https://github.com/lynchjames/note-refactor-obsidian#usage)?

**Comment by mafsi** [comment]
@DutchPete  use this: https://www.screentogif.com/

**Comment by DutchPete** [comment]
I updated and refreshed: no change.

My use is the top line in the table.

**Comment by lynchjames** [comment]
Were there any square brackets around content you were copying where the closing `]]` may not have been included in the selection? 

I've found with your custom css some cases where an entire paragraphs of content can seem to disappear if there are unpaired `[[` characters. Here is a demo of the issue, you can see the keys I'm using.

[CSS hiding content demo](https://user-images.githubusercontent.com/113271/97924456-97bc6a80-1d57-11eb-8dd5-55c096be833d.gif)

However, you did say that you were still having the issue with custom CSS turned off. I have experienced a couple of cases of the plugin not being fully reloaded unless it is turned it off and then back on again using the toggle on the Third Party plugins pane in Obsidian settings. Could you update to latest and try turning the plugin off and then on to see if you're still having the issue?

**Comment by DutchPete** [comment]
There are no unpaired`[[` characters in my file. If you don't see them it means they are hidden with the "remove clutter" code, but they are present.

Anyway, I updated the plug-in, turned it off then back on, but no luck.
I also tried it on a default vault, i.e. one with no custom CSS, same result. I even closed that vault, reopened it, retried, still no luck.

**Comment by DutchPete** [comment]
I updated to 1.4.5 but it still does not work for me. It seems that I am the only one with this bug that is unfixable, so I will uninstall the plug-in. A pity because I would use it a lot.

**Comment by DutchPete** [comment]
GOOD NEWS !!

I went ahead and uninstalled the plug-in, frustrated. Then I had a "brainwave": try re-installation. Yep, bingo, now it works!

Re Splitting: am I right when I say Splitting is when you want to extract more than a section, like e.g. half the note, you can use Splitting rather than having to manually select that big section/half the note?

**Comment by mafsi** [comment]
> am I right when I say Splitting is when you want to extract more than a section, like e.g. half the note, you can use Splitting rather than having to manually select that big section/half the note?

Yeah. Thatțs the ideea. You find that a note is good to split from the cursor to the bottom

**Comment by lynchjames** [comment]
That's great new @DutchPete! Will close this issue.
