### ISSUE TITLE
Almost all the functions of the plug-in do not work

### ISSUE THREAD

**Issue by zhl111** [lynchjames/note-refactor-obsidian#74]
Don't know how to troubleshoot
![image](https://user-images.githubusercontent.com/29135984/158050547-1db23515-4cdf-4c57-84c0-80c39002e7ab.png)

**Comment by lynchjames** [comment]
I think this was a bug in Obsidian code as `generateMarkdowLink` is an Obsidian FileManager function. Closing as no-fix.
